name: biocIBC_ROC

on: [pull_request]
jobs:
  install1:
    container: vjcitn/vjcbbs_support:v8
    name: install with log
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: ROC
    steps:
    - name: install and log bioc package from bioc git  # 3.10 owing to :v8 above
      run: |
        Rscript -e "BiocManager::install('${PACKAGE_NAME}')" > install.log.txt
        git clone https://git.bioconductor.org/packages/${PACKAGE_NAME}
        setwd ${PACKAGE_NAME}
        Rscript -e "devtools::check()" > chk.log.txt
    - name: get install log
      uses: actions/upload-artifact@v1
      with:
        name: install_log
        path: install.log.txt
    - name: get chk log
      uses: actions/upload-artifact@v1
      with:
        name: chk_log
        path: chk.log.txt
  
