name: biocIBC_ROC

on: [pull_request]
jobs:
  install1:
    container: vjcitn/vjcbbs_support:v8
    name: install with log.txt
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: ROC
      TARBALL: to_do
    steps:
    - name: improve
      run: |
        sudo apt-get update -y
        sudo apt-get install -y qpdf
      continue-on-error: true
    - name: install and log bioc package from bioc git  # 3.10 owing to :v8 above
      run: |
        Rscript -e "BiocManager::install('${PACKAGE_NAME}')" > install.log.txt
        git clone https://git.bioconductor.org/packages/${PACKAGE_NAME}
        cd ${PACKAGE_NAME}
        Rscript -e "devtools::check()" > ../chk.log.txt 
        cd ..
        R CMD build ${PACKAGE_NAME}
        export TARBALL=`ls ${PACKAGE_NAME}_*.gz`
        cp ${TARBALL} /home/runner/work/biocIBC/biocIBC/
        echo `pwd`
        ls
      continue-on-error: true
    - name: get install log
      uses: actions/upload-artifact@v1
      with:
        name: install_log
        path: install.log.txt
      continue-on-error: true
    - name: get chk log
      uses: actions/upload-artifact@v1
      with:
        name: chk_log
        path: chk.log.txt
      continue-on-error: true 
    - name: get tarball
      uses: actions/upload-artifact@v1
      with:
        name: tb
        path: ROC_1.63.0.tar.gz # not substituting?
  
