name: biocIBC_ROC

on: [pull_request]
jobs:
  install1:
    container: vjcitn/vjcbbs_support:v8
    name: install with log
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: install and log bioc package from bioc git  # 3.10
      run: Rscript -e "BiocManager::install('ROC')" > roc_install.log.txt
    - name: get install log
      uses: actions/upload-artifact@v1
      with:
        name: install_log
        path: roc_install.log.txt
  build1: 
    container: vjcitn/vjcbbs_support:v8
    needs: install1
    name: build with log 
    runs-on: ubuntu-latest
    steps:
      - name: build and log bioc package from bioc git
        run: Rscript -e "git2r::clone('https://git.bioconductor.org/packages/ROC', 'ROC', branch='RELEASE_3_10'); setwd('ROC'); pkgbuild::build()" > roc_build.log.txt
      - name: get build log
        uses: actions/upload-artifact@v1
        with:
          name: build_log
          path: roc_build.log.txt
      - name: get tarball
        uses: actions/upload-artifact@v1
        with: 
          name: tarball
          path: ROC_1.62.0.tar.gz
  check1:
    container: vjcitn/vjcbbs_support:v8
    needs: build1
    name: check with log 
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v1
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: tarball
          path: ROC_1.62.0.tar.gz
      - name: check and log bioc package from bioc git 
        run: R CMD check ROC_1.62.0.tar.gz > roc_chk.log.txt
      - name: get check log
        uses: actions/upload-artifact@v1
        with:
          name: check_log
          path: roc_chk.log.txt
