name: rocci

on: [push]
jobs:
  install1:
    container: vjcitn/vjcbbs_support:v5
    name: install with log
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install and log bioc package from personal github
      run: Rscript -e "BiocManager::install('ROC')" > roc_install.log.txt
    - name: get install log
      uses: actions/upload-artifact@v1
      with:
        name: install_log
        path: roc_install.log.txt
  build: 
    container: vjcitn/vjcbbs_support:v5
    needs: install1
    name: build with log 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build and log bioc package from personal github 
        run: Rscript -e "git2r::clone('https://git.bioconductor.org/packages/ROC', 'ROC'); setwd('ROC'); pkgbuild::build()" > roc_build.log.txt
      - name: get build log
        uses: actions/upload-artifact@v1
        with:
          name: build_log
          path: roc_build.log.txt
      - name: get tarball
        uses: actions/upload-artifact@v1
        with: 
          name: tarball
          path: ROC_1.61.0.tar.gz
